_wandb:
    value:
        cli_version: 0.25.1
        e:
            6t38obieiilc4fcqvmrenhx0fqf5w36h:
                codePath: examples\run_cifar10.py
                codePathLocal: examples\run_cifar10.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "297238786048"
                        used: "189874262016"
                email: fann2025@lzu.edu.cn
                executable: D:\Python\Python312\python.exe
                host: DESKTOP-7NVS1P4
                memory:
                    total: "16805056512"
                os: Windows-11-10.0.26200-SP0
                program: d:\研究生学习\论文-联邦学习\联邦学习代码\examples\run_cifar10.py
                python: CPython 3.12.7
                root: D:\研究生学习\论文-联邦学习\联邦学习代码
                startedAt: "2026-04-15T13:04:13.434176Z"
                writerId: 6t38obieiilc4fcqvmrenhx0fqf5w36h
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.7
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
batch_size:
    value: 32
data_path:
    value: C:/Users/Fnn/CascadeProjects/federated_learning_cifar10_mnist/data
device:
    value: cpu
dirichlet_alpha:
    value: 0.1
eval_interval:
    value: 10
fraction:
    value: 0.4
local_epochs:
    value: 1
lr:
    value: 0.01
lr_decay:
    value: 0.992
lr_decay_step:
    value: 1
nesterov:
    value: true
num_clients:
    value: 10
optimizer_momentum:
    value: 0.9
partition_method:
    value: dirichlet
results_path:
    value: D:\研究生学习\论文-联邦学习\联邦学习代码
rounds:
    value: 300
server_momentum_beta:
    value: 0.9
wandb_name:
    value: cifar10-dirichlet
wandb_project:
    value: federated-learning-cifar10
weight_decay:
    value: 0.0001
