_wandb:
    value:
        cli_version: 0.25.1
        e:
            lsymk6lxgmqxzpi4qirk7lv68spfysra:
                codePath: examples\run_mnist.py
                codePathLocal: examples\run_mnist.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "297238786048"
                        used: "188240539648"
                email: fann2025@lzu.edu.cn
                executable: D:\Python\Python312\python.exe
                host: DESKTOP-7NVS1P4
                memory:
                    total: "16805056512"
                os: Windows-11-10.0.26200-SP0
                program: d:\研究生学习\论文-联邦学习\联邦学习代码\examples\run_mnist.py
                python: CPython 3.12.7
                root: D:\研究生学习\论文-联邦学习\联邦学习代码
                startedAt: "2026-04-13T11:19:24.497223Z"
                writerId: lsymk6lxgmqxzpi4qirk7lv68spfysra
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.7
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
batch_size:
    value: 10
data_path:
    value: C:/Users/Fnn/CascadeProjects/federated_learning_cifar10_mnist/data
device:
    value: cpu
fraction:
    value: 0.1
iid:
    value: true
local_epochs:
    value: 10
lr:
    value: 0.01
num_clients:
    value: 10
results_path:
    value: D:\研究生学习\论文-联邦学习\联邦学习代码
rounds:
    value: 10
wandb_name:
    value: mnist-fedavg
wandb_project:
    value: federated-learning-mnist
