_wandb:
    value:
        cli_version: 0.25.1
        e:
            99bm6mo6iw7g7mva7uo6yeim2zcetwab:
                codePath: examples\run_cifar10.py
                codePathLocal: examples\run_cifar10.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "297238786048"
                        used: "189860184064"
                email: fann2025@lzu.edu.cn
                executable: D:\Python\Python312\python.exe
                host: DESKTOP-7NVS1P4
                memory:
                    total: "16805056512"
                os: Windows-11-10.0.26200-SP0
                program: d:\研究生学习\论文-联邦学习\联邦学习代码\examples\run_cifar10.py
                python: CPython 3.12.7
                root: D:\研究生学习\论文-联邦学习\联邦学习代码
                startedAt: "2026-04-15T08:03:12.854044Z"
                writerId: 99bm6mo6iw7g7mva7uo6yeim2zcetwab
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.7
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
batch_size:
    value: 32
data_path:
    value: C:/Users/Fnn/CascadeProjects/federated_learning_cifar10_mnist/data
device:
    value: cpu
dirichlet_alpha:
    value: 0.5
fraction:
    value: 0.4
local_epochs:
    value: 1
lr:
    value: 0.02
num_clients:
    value: 10
partition_method:
    value: dirichlet
results_path:
    value: D:\研究生学习\论文-联邦学习\联邦学习代码
rounds:
    value: 50
server_momentum_beta:
    value: 0.5
wandb_name:
    value: cifar10-dirichlet
wandb_project:
    value: federated-learning-cifar10
